FROM golang:1.26-bookworm

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

# Pre-compile integration test binary
RUN go test -tags integration -c -o /app/integration.test ./integration

ENTRYPOINT ["/app/integration.test"]
